name: tests

permissions:
    id-token: write  # required for requesting the JWT
    contents: read  # required for actions/checkout

on:
    push:
        branches:
            - "tests-infra-pytest"

jobs:
    python-job:
        name: "PyTest tests"
        runs-on: ubuntu-latest
        environment: "test"

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Setup Python
            uses: actions/setup-python@v3
            with:
                python-version: '3.11.4'

          - name: Assume Github OIDC role
            uses: aws-actions/configure-aws-credentials@v2
            with:
                aws-region: us-west-2
                role-to-assume: arn:aws:iam::916098889494:role/GithubOIDCRole-MAAP-Project-maap-eoapi-test
                role-session-name: maap-eoapi-test

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r tests/requirements.txt

          - name: Run pytest
            env:
                INGESTOR_URL: ${{ vars.INGESTOR_URL }}
                STAC_REGISTER_SERVICE_ID: ${{ vars.STAC_REGISTER_SERVICE_ID }}
                REGION_NAME: "us-west-2"
                COGNITO_DOMAIN: ${{ vars.COGNITO_DOMAIN }}
                SCOPE: ${{ vars.SCOPE }}
            run: |
                pytest tests